### ISSUE TITLE
May not be a good idea to make this repository public.

### ISSUE THREAD

**Issue by garywei944** [lilingxi01/umass_cs121_hub#1]
Just a kindly remind I don't know how it is for cs 121, I'm taking cs 230 this semester, and it's said someone has been called in because of posting course materials publicly. 
![image](https://user-images.githubusercontent.com/33930674/70499511-4b38c280-1ae7-11ea-9e6c-e60001665106.png)

Also, FYI, I found this on the syllabus of  cs230 this semester: https://docs.google.com/document/d/1-KyMxI6O_KuZ4IPE7jkegyfuvE6jSzeU9uPGH3-Ria4/edit
![image](https://user-images.githubusercontent.com/33930674/70499862-17aa6800-1ae8-11ea-9fcb-2f5f715c8bef.png)

Take care!

**Comment by lilingxi01** [comment]
Thanks for your advice.
I will change it to a private repo.

**Comment by garywei944** [comment]
Not a problem! Good luck with final :)
